version: '3'
services:
    nginx:
        image: nginx
        container_name: sf4_nginx
        ports:
          - 8080:80
          - 443:443
        volumes:
          - .docker/config/vhosts/sf4-nginx.conf:/etc/nginx/conf.d/default.conf:ro
          - ./src:/var/www/html
        depends_on:
          - php-fpm
          - phpmyadmin

    mysql:
        image: mysql
        container_name: sf4_mysql
        command: "--default-authentication-plugin=mysql_native_password"
        restart: always
        volumes:
          - ./.docker/data/db:/docker-entrypoint-initdb.d
          - ./.docker/data/lib:/var/lib/mysql
        ports:
          - 3306:3306
        environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=dummy
        - MYSQL_USER=dummy
        - MYSQL_PASSWORD=dummy
    php-fpm:
        build: .docker/php
        container_name: sf4_php
        volumes:
          - ./src:/var/www/html
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=dummy
          - MYSQL_USER=dummy
          - MYSQL_PASSWORD=dummy
        depends_on:
          - mysql
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - mysql:db
      ports:
        - "8082:80"
      environment:
        - PMA_USER=dummy
        - PMA_PASSWORD=dummy
        - PHP_UPLOAD_MAX_FILESIZE=100MB
